### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by JoseJCanedo** [CSU-WebDev/trashbusters_frontend#32]
https://github.com/CSU-WebDev/trashbusters_frontend/blob/3471606100240b80228fc6502190235e90919a4f/src/scss/variables.scss#L1

Use more generic names for the colors. White could be just white-color, background if used in more places you can name as "primary" or something if you plan to theme

**Comment by austinProGit** [comment]
I now understand the concept of loose coupling with respect to SASS variables. I have changed my code to the following: 
$white-color: white;
$nav-footer-color: $white-color;
$font-family_1: "Lucida Bright", Georgia, serif;
$background-color_1: #658E9C;
$background-color_2: #004D21;
$background-color_3: rgb(136, 123, 10);
