### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by JoseJCanedo** [CSU-WebDev/trashbusters_frontend#33]
https://github.com/CSU-WebDev/trashbusters_frontend/blob/3471606100240b80228fc6502190235e90919a4f/src/scss/navigationbar.scss#L22

Create variables for the font sizes so you can change them all at once

**Comment by austinProGit** [comment]
Completed: 
$white-color: white;
$nav-footer-color: $white-color;
$font-family_1: "Lucida Bright", Georgia, serif;
$background-color_1: #658E9C;
$background-color_2: #004D21;
$background-color_3: rgb(136, 123, 10);
$small-font: large;
$medium-font: x-large;
$large-font: xx-large;
$light-gray: gray;
$medium-gray: rgb(87, 87, 87);
$dark-gray: rgb(34, 34, 34);
