### ISSUE TITLE
Pretty and Ugly pic

### ISSUE THREAD

**Issue by JoseJCanedo** [CSU-WebDev/trashbusters_frontend#42]
https://github.com/CSU-WebDev/trashbusters_frontend/blob/3471606100240b80228fc6502190235e90919a4f/src/components/UglyPic.jsx#L1

They're the same component, but with a different image url. Can't they be one component and just pass the correct image down to one or the other?

**Comment by austinProGit** [comment]
I have deleted the two original components and replaced them with a new component: Pic.jsx: 
import React from 'react'
import Image from 'react-bootstrap/Image'

export default function UglyPic(props) {
    return (
        <Image  className='pic' src={props.src} fluid/>
    )
}

Note: I am unable to simply pass a file path as the src prop for some reason. Here is my new Pics.jsx component: 
import React from 'react'
import Pic from './Pic'
import { Container, Row, Col } from 'react-bootstrap'
import UglyPicture from '../images/litter-before.jpg'
import PrettyPicture from '../images/litter-after.jpg'

export default function Pics() {
    return (
        <Container id='pics-container' className='mt-4 mb-4'>
            <Row className="justify-content-center">
                <Col s={12} md={6} className="align-items-center">
                    <Pic src={UglyPicture} />
                </Col>
                <Col s={12} md={6} className="align-items-center">
                    <Pic src={PrettyPicture} />
                </Col>
            </Row>
        </Container>
    )
}
