### ISSUE TITLE
change

### ISSUE THREAD

**Issue by JoseJCanedo** [CSU-WebDev/trashbusters_frontend#43]
https://github.com/CSU-WebDev/trashbusters_frontend/blob/3471606100240b80228fc6502190235e90919a4f/src/components/TrashMap.jsx#L86

change to console.warn if you don't plan to error handle, although I would suggest a small popup modal or something would be good to let the person know something happened

**Comment by austinProGit** [comment]
Popup modal created. Michael is taking on testing and styling.
