### ISSUE TITLE
Hard to read, formatting

### ISSUE THREAD

**Issue by JoseJCanedo** [CSU-WebDev/trashbusters_frontend#47]
https://github.com/CSU-WebDev/trashbusters_frontend/blob/3471606100240b80228fc6502190235e90919a4f/src/components/TrashMap.jsx#L139

**Comment by austinProGit** [comment]
I have added an extra space like so to aid in ease of reading: 
        {marker && (
          <MarkerF id='selected-marker' key={marker} position={marker}>
            <InfoWindowF 
              onCloseClick={() => {
                setMarker(null)
              }} 
              position={marker}>
              <div style={infoWindowStyle}>
                <p>Latitude: {marker.lat.toFixed(6)}</p>
                <p>Longitude: {marker.lng.toFixed(6)}</p>
                <input id='new-pin-desc-input' style={infoWindowInputStyle} type="text" value={desc} onChange={handleDescriptionChange} placeholder="Enter description" />
                <button id='save-btn' style={{...infoWindowSaveBtnStyle, ...infoWindowBtnStyle}} onClick={handleSavePointClick}>Save Point</button>
              </div>
            </InfoWindowF>
          </MarkerF>
        )}
