### ISSUE TITLE
Duplicate code

### ISSUE THREAD

**Issue by JoseJCanedo** [CSU-WebDev/trashbusters_frontend#48]
https://github.com/CSU-WebDev/trashbusters_frontend/blob/3471606100240b80228fc6502190235e90919a4f/src/components/TrashMap.jsx#L29

You should be able to combine mostly with infoWindowDeleteBtnStyle. You can create a new variable with all the common info and then combine them using a spread operator when you pass it to the component that uses the info https://www.w3schools.com/react/react_es6_spread.asp

**Comment by austinProGit** [comment]
I understand that I was duplicating code. To fix this, I changed my code to the following: 

const infoWindowBtnStyle = {
  border: 'none',
  color: 'white',
  padding: '10px 20px',
  fontSize: '16px',
  borderRadius: '5px',
  marginTop: '10px'
}

const infoWindowSaveBtnStyle = {
  backgroundColor: '#4CAF50',
}

const infoWindowDeleteBtnStyle = {
  backgroundColor: 'red',
}

<button style={{...infoWindowSaveBtnStyle, ...infoWindowBtnStyle}} onClick={handleSavePointClick}>Save Point</button>

The code is functioning properly. I chose to keep my in-line styles using locally defined constants, as that appears to be the best practice for this type of component as evidenced by the following documentation:

https://github.com/JustFly1984/react-google-maps-api/blob/master/packages/react-google-maps-api-gatsby-example/src/examples/example-shapes.tsx
